### DISCUSSION TITLE
Why is my Tesla not charging?

### DISCUSSION THREAD

**Discussion by GuusRemmerswaal** [tdorssers/TeslaPy#165] [Q&A]
Hi all. Still pretty new here. I got some help to get EVCC up and running yesterday. Currently I can see my grid power meter and my Tesla SOC, charge limit, but it won't start charging.

I'm expecting EVCC to use the Tesla API to control charging. My charger is a 1st gen Tesla Wall Connector, so that can't be controlled programmatically. I have added a dummy charger to get EVCC to start properly.

Is my setup suitable for EVCC at all? Can anyone spot the problem?

<details><summary>Konfiguration (/app/evcc.yaml)</summary>

```yaml
# open evcc at http://evcc.local:7070
network:
  schema: http
  host: evcc.local # .local suffix announces the hostname on MDNS
  port: 7070

log: debug
levels:
  cache: error

# unique installation id
plant: *****

interval: 5s # control cycle interval

sponsortoken: *****

# sponsors can set telemetry: true to enable anonymous data aggregation
# see https://github.com/evcc-io/evcc/discussions/4554
telemetry: false

meters:
- type: template
  template: homewizard
  usage: grid
  host: 192.168.2.103
  name: grid1

chargers:
  - name: dummy_charger
    type: custom
    status: # charger status A..F
      source: script
      cmd: /bin/sh -c 'echo b'
    enabled: # charger enabled state (true/false or 0/1)
      source: script
      cmd: /bin/sh -c 'echo true'
    enable: # set charger enabled state (true/false or 0/1)
      source: script
      cmd: /bin/sh -c 'echo true'
    maxcurrent: # set charger max current (A)
      source: script
      cmd: /bin/sh -c 'echo 16'

loadpoints:
  - title: Oprit # display name for UI
    charger: dummy_charger # charger reference
    vehicle: ev2 # reference to standard vehicle
    mode: pv # charge mode (off, now, minpv, pv)

vehicles:
- type: template
  template: tesla
  title: Timo
  accessToken: *****
  refreshToken: *****
  vin: *****
  capacity: 75
  name: ev2
  control: true

site:
  title: Thuis
  meters:
    grid: grid1
```

</details>
Version: `0.127.3`
